ViewComponents/ModalViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.ViewComponents
{
    public class ModalViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string id, string type)
        {
            ViewData["id"] = id;

            return type switch
            {
                "delete" => View("Delete"),
                _ => View("Delete"),
            };
        }
    }
}

Views/Dashboard/Crud.cshtml
@using Core.ViewModel
@model ChildrenVM 
@* @using Core.Enumerators *@
@{
    Layout = "_Layout";
    ViewData["Title"] = "Incluir/Editar";
}

<form id="frm-crud" class="frm-crud" asp-action="Crud" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" id="btnSubmit" class="d-none"></button>
    <div class="div-title-page">
        <h4 class="m-0">Cadastro de Setores</h4>
        <div class="actions-page">
              
            <button onclick="controller.save()" type="submit" class="btn btn-primary me-2" data-bs-toggle="tooltip" data-bs-placement="top" title="Salvar">
                <i class="fa-solid fa-floppy-disk"></i>
                <span class="d-none d-sm-inline">Salvar</span>
            </button>
            
            <a href="/Children" class="btn btn-danger" data-bs-toggle="tooltip" data-bs-placement="top" title="Voltar">
                <i class="fa-solid fa-arrow-left"></i>
                <span class="d-none d-sm-inline">Voltar</span>
            </a>
        </div>
    </div>
    <div class="div-page-crud">
        <div class="col-lg-12 col-md-10 col-sm-12 col-12 d-flex align-items-center">
            <div class="row g-2 m-0 w-100">

                <div class="col-12">
                    <label class="form-label">
                        Nome
                    </label>
                    <input asp-for="Name"
                           maxlength="100"
                           class="form-control"
                           required
                           valid-message="Nome é obrigatório"
                           placeholder="Digite o nome aqui..." />
                </div>

                <div>
                    <label class="form-label">
                        Responsável
                    </label>
                    <select-responsable asp-for="UserId" class="form-control" gr-vl-edit="@Model.UserId"
                                        required
                                        valid-message="Responsável é obrigatório" />
                </div>

               
                <div class="w-100"></div>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <environment names="Development">
        <script src="~/js/children/crud.js"></script>
    </environment>
    <environment names="Production">
        <script src="~/js/children/crud.min.js"></script>
    </environment>
}

Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Children";
}

<div id="div-content" class="card shadow-sm sg-content">
    <div class="card-body">
        <div class="row justify-content-center">

            

        </div>
    </div>
</div>

<div class="div-page-list">
    <div class="table-responsive overflow-hidden">
         <table id="tbl-items" class="table table-striped table-bordered w-100 m-0">
            <thead>
                <tr>
                    <th property="Id" width="70">Cód.</th>
                    <th property="Buttons" width="100" class="text-center">Ações</th>
                    <th property="Name">Nome</th>
                    <th property="BtnQ1">Quest 1</th>
                    <th property="BtnQ2">Quest 2</th>

                </tr>
            </thead>
            <tbody>
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>

                </tr>
            </tfoot>
        </table> 
    </div>
</div>

@await Component.InvokeAsync("Modal", new { id = "item", type = "delete" })

@section Scripts {
    <environment names="Development">
        <script src="~/js/common/table_gr.js" asp-append-version="true"></script>
        <script src="~/js/dashboard/index.js" asp-append-version="true"></script>
    </environment>
    <environment names="Production">
        <script src="~/js/common/table_gr.min.js" asp-append-version="true"></script>
        <script src="~/js/dashboard/index.min.js" asp-append-version="true"></script>
    </environment>
}