Controllers/HomeController.cs
using System.Diagnostics;
using Core.Enumerators;
using Core.ViewModel;
using Microsoft.AspNetCore.Mvc;
using HPLFelixMecca.Controllers;

namespace HPLFelixMecca.Controllers
{
    public class HomeController : ControllerBaseCore
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var canView = await GetCanViewAsync(model.);

            ViewBag.CanView = canView;

            return View();
        }

        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponents/CardModuleViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.ViewComponents_old
{
    public class CardModuleViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string controllerName, string action, string title, string icon)
        {
            if (string.IsNullOrEmpty(action))
                ViewData["controllerName"] = controllerName;
            else
                ViewData["controllerName"] = $"{controllerName}/{action}/";
            ViewData["action"] = action;
            ViewData["title"] = title;
            ViewData["icon"] = icon;

            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="div-content" class="card shadow-sm sg-content">
    @* <div class="card-body"> *@
        <div class="row justify-content-center">

            @await Component.InvokeAsync("CardModule", new { controllerName = "Control", title = "Controle", icon = "fa-solid fa-users" })
            @await Component.InvokeAsync("CardModule", new { controllerName = "Dashboard", title = "Acompanhamento", icon = "fa-solid fa-people-carry-box" })
            @await Component.InvokeAsync("CardModule", new { controllerName = "Children", title = "Dependentes", icon = "fa-solid fa-users" })
            @await Component.InvokeAsync("CardModule", new { controllerName = "User", actionName = "Minhas informações", title = "Informações", icon = "fa-solid fa-people-carry-box" })
        </div>
    @* </div> *@
</div>